# encoding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Move.create(:name => 'Leuanveto myötäotteella')
Move.create(:name => 'Hauiskääntö tangolla')
Move.create(:name => 'Hauiskääntö taljassa narulla')
Move.create(:name => 'Hauiskääntö käsipainoilla')
Move.create(:name => 'Pystypunnerrus')
Move.create(:name => 'Olankohautus käsipainoilla')
Move.create(:name => 'Vipunosto eteen käsipainoilla')
Move.create(:name => 'Vipunosto sivuille käsipainoilla')
Move.create(:name => 'Pystysoutu tangolla')
Move.create(:name => 'Takaolkapäälaite')
Move.create(:name => 'Vinopenkki')
Move.create(:name => 'Vinopenkki käsipainoilla')
Move.create(:name => 'Vipunosto käsipainoilla')
Move.create(:name => 'Punnerrus ristikkäistaljassa')
Move.create(:name => 'Penkkipunnerrus')
Move.create(:name => 'Penkkipunnerrus käsipainoilla')
Move.create(:name => 'Leuanveto vastaotteella')
Move.create(:name => 'Dippi')
Move.create(:name => 'Ranskalainen punnerrus')
Move.create(:name => 'Ojentajapunnerrus köydellä')
Move.create(:name => 'Ojentajapunnerrus köydellä pään yli')
Move.create(:name => 'Ojentajapunnerrus pään yli käsipainolla')
Move.create(:name => 'Kyykky')
Move.create(:name => 'Jalkaprässi')
Move.create(:name => 'Pohjelaite')
Move.create(:name => 'Takareisilaite')
Move.create(:name => 'Etureisilaite')
Move.create(:name => 'Maastaveto')
Move.create(:name => 'Leuanveto vastaotteella')
Move.create(:name => 'Soutu käsipainolla')
Move.create(:name => 'Alaselkäliike')
Move.create(:name => 'Ylätalja')
Move.create(:name => 'Alatalja')
Move.create(:name => 'Vatsalihakset voimapyörällä')
